

## ###########
## # Options #
## ###########

# zsh as default shell
set -g default-shell /bin/zsh

# Mouse and clipboard control
set -g mouse on
set -g set-clipboard on


## #########
## # Binds #
## #########

# ctrl space as prefix
unbind C-b
set -g prefix C-Space
bind-key C-Space send-prefix

# Switch panes with alt arrows
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Switch windows with ctrl alt arrows
bind -n C-M-Left previous-window
bind -n C-M-Right next-window

# Split to directions with arrows
bind-key Up split-window -v -b -c "#{pane_current_path}"
bind-key Down split-window -v -c "#{pane_current_path}"
bind-key Left split-window -h -b -c "#{pane_current_path}"
bind-key Right split-window -h -c "#{pane_current_path}"

# Quick command prompt
unbind ':'
bind-key ';' command-prompt

# VI copy mode binds
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane


## ##############
## # Appearance #
## ##############

# Full terminal colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"

# Neovim integration
set -g focus-events on
set -g status-left-length 99
set -g status-right-length 99
set -g status-justify centre

# Adapted Moonfly theme
set -g message-style "bg=#131313,fg=#9c9c9c"
set -g pane-active-border-style "bg=#080808,fg=#80a0ff"
set -g pane-border-style "bg=#080808,fg=#303030"
set -g status-style "bg=#131313,fg=#9c9c9c"
setw -g window-status-activity-style none
setw -g window-status-current-style "bg=#353946,fg=#9c9c9c"

# Set active and inactive window style.
setw -g window-status-current-format "#[bg=#131313]#[fg=#353946]#[bg=default]#[fg=#80a0ff] #I#{?window_flags,#{window_flags}, } #W #[bg=#131313]#[fg=#353946]"
setw -g window-status-format "#[bg=#131313]  #I#{?window_flags,#{window_flags}, } #W  "

# Set status bar components and style.
set -g status-left "#[bg=#80a0ff]#[fg=#1c1c1c] #h #[fg=#80a0ff]#[bg=#303030] session #S #[fg=#303030]#[bg=default]#[fg=#9c9c9c] #{pane_current_path}"
set -g status-right "#[fg=#9c9c9c]#{pane_current_command} #[fg=#303030]#[fg=#80a0ff]#[bg=#303030] %a %d %b #[bg=#80a0ff]#[fg=#1c1c1c] %H:%M "

