

## ###########
## # Options #
## ###########

# zsh as default shell
set -g default-shell /bin/zsh

# Mouse and clipboard control
set -g mouse on
set -g set-clipboard on


## #########
## # Binds #
## #########

# ctrl space as prefix
unbind C-b
set -g prefix C-Space
bind-key C-Space send-prefix

# Switch panes with alt arrows
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Switch windows with ctrl alt arrows
bind -n C-M-Left previous-window
bind -n C-M-Right next-window

# Split to directions with arrows
bind-key Up split-window -v -b -c "#{pane_current_path}"
bind-key Down split-window -v -c "#{pane_current_path}"
bind-key Left split-window -h -b -c "#{pane_current_path}"
bind-key Right split-window -h -c "#{pane_current_path}"

# Quick command prompt
unbind ':'
bind-key ';' command-prompt

# VI copy mode binds
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane


## #########
## # Other #
## #########

# Full terminal colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"

# Start on last session
new-session -n $HOST

